FROM zixia/wechaty

WORKDIR /bot/

ONBUILD ARG NODE_ENV
ONBUILD ENV NODE_ENV $NODE_ENV

ONBUILD COPY package.json /bot/
ONBUILD RUN npm install && npm cache clean
ONBUILD COPY . /bot/

CMD [ "npm", "start" ]
