FROM zixia/wechaty

RUN sudo mkdir /app/ \
  && chown -R bot:bot /app/
WORKDIR /app/

ONBUILD ARG NODE_ENV
ONBUILD ENV NODE_ENV $NODE_ENV

ONBUILD COPY package.json .
ONBUILD RUN npm install && npm cache clean && rm -fr /tmp/* /root/.npm
ONBUILD COPY . .

CMD [ "npm", "start" ]
