name: 🚀 Wechaty Feature Request
description: I have a suggestion (and might want to implement myself 🙂)!
title: "[FEATURE]: "
labels: ["feature request", "enhancement"]
body:
  - type: textarea
    id: feature-req
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
       A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
       A clear and concise description of what you want to happen.
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered
      description: |
       A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: addition
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.