export const WECHATY_PUPPET_PADCHAT_ENDPOINT = process.env['WECHATY_PUPPET_PADCHAT_ENDPOINT']  || 'ws://101.132.129.155:9091/wx'
export const WECHATY_PUPPET_PADCHAT_TOKEN    = process.env['WECHATY_PUPPET_PADCHAT_TOKEN']     || 'padchattest'
